### ISSUE TITLE
[Module] Anti bootloop

### ISSUE THREAD

**Issue by nedorazrab0** [Magisk-Modules-Alt-Repo/submission#211] opened 2023-12-28 20:55 UTC
### ID

abootloop

### Name

Anti bootloop

### Description

Protection from bootloop. Press power key at boot to disable magisk modules

### Module repository link

https://github.com/nedorazrab0/abootloop

**Comment by DerGoogler** [comment] 2023-12-30 19:22
This might be a duplicate of https://github.com/Magisk-Modules-Alt-Repo/Simple_BootloopSaver/issues

@Atrate what do you think?

**Comment by Atrate** [comment] 2024-01-01 15:31
> This might be a duplicate of https://github.com/Magisk-Modules-Alt-Repo/Simple_BootloopSaver/issues
> 
> @Atrate what do you think?

Seems it accomplishes the same thing but with a starkly different method. As long as the module itself does not cause a bootloop (by e.g. waiting for the keypress indefinitely), I think that's a nice addition to the repo - if one of the two modules breaks, at least end users will have a fallback.

**Comment by Atrate** [comment] 2024-02-03 11:04
@nedorazrab0 Have you tested your module to see that it works properly?

**Comment by Atrate** [comment] 2024-02-03 12:03
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/abootloop, enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.

**Closed by Atrate** 2024-02-03 12:03 UTC
Labels: module, approved
