### ISSUE TITLE
[Module] 36 DPI NavBar

### ISSUE THREAD

**Issue by CrazyBytesVE** [Magisk-Modules-Alt-Repo/submission#103] opened 2022-07-18 13:20 UTC
**Name**: 36 DPI NavBar
**Description**:  Reduce el tamaño de la barra de navegación a 36 DPI, maximizando el espacio en pantalla disponible
**Link**: https://github.com/CrazyBytesVE/36-DPI-NavBar-Mod

**Comment by HuskyDG** [comment] 2022-07-29 08:11
Can you give description in English? Thanks

**Comment by Atrate** [comment] 2022-07-29 10:20
Duplicate of #101

**Closed by Atrate** 2022-07-29 10:20 UTC
Labels: module, please fix

**Comment by CrazyBytesVE** [comment] 2022-07-31 14:04
> Can you give description in English? Thanks

Reduces the size of the navigation bar to 36 DPI, maximizing the available screen real estate
Link: https://github.com/CrazyBytesVE/36-DPI-NavBar-Mod
